version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - springboot-api

networks:
  app-network:
    external: true