server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: http://springboot-api:8080
          predicates:
            - Path=/api/productos/**
          filters:
            - name: CircuitBreaker
              args:
                name: productoCB
                fallbackUri: forward:/default

        - id: producto-service-simple
          uri: http://springboot-api:8080
          predicates:
            - Path=/
          filters:
            - RewritePath=/(.*), /api/productos
            - name: CircuitBreaker
              args:
                name: productoCB
                fallbackUri: forward:/default
