server:
  port: 9091

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://127.0.0.1:5501"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
      routes:
        - id: producto-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/productos/**
          filters:
            - name: CircuitBreaker
              args:
                name: productoCB
                fallbackUri: forward:/default