server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: http://localhost:8080
          predicates:
            - Path=/
          filters:
            - RewritePath=/(.*), /api/productos

        - id: producto-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/productos/**